// ═══════════════════════════════════════════════════════════════
//  AASHISH KE SAARE POSTS — YAHAN ADD KARO
//
//  aspect: 'portrait'  → Reels/Stories (9:16 tall)
//          'square'    → Instagram Posts (1:1)
//          'landscape' → Videos/YouTube (16:9 wide)
//          'wide'      → Cinematic (21:9 extra wide)
//
//  thumb:  Post ki thumbnail image URL (Instagram/YouTube se copy karo)
//          Khaali '' rakho — stylish gradient auto dikhega
//
//  postUrl: Direct link — click karne par seedha wahan jayega
// ═══════════════════════════════════════════════════════════════

export type Post = {
  id: string
  cat: string
  platform: 'instagram' | 'youtube' | 'facebook'
  postUrl: string
  thumb: string
  title: string
  desc: string
  year: string
  aspect: 'portrait' | 'square' | 'landscape' | 'wide'
}

export const POSTS: Post[] = [
  {
    id: 'reel-001',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DVsjSElDBiK/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781158135/Image-575_vbrmu1.jpg',
    title: 'Brand Awareness Reel',
    desc: 'High-engagement brand reel for Karmyug Techzone.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'reel-002',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DM9kFvxNX5E/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781159831/Image-587_utk2pu.jpg',
    title: 'Product Showcase Reel',
    desc: 'Fast-paced product reveal reel with trending audio.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'reel-003',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DMX_thDP7H1/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781162337/Image-643_xhd52q.jpg',
    title: 'Trending Reel',
    desc: 'Viral-format reel boosting reach organically.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'reel-004',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DMMuu3esKrm/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781164000/Image-505_jvqptm.jpg',
    title: 'Trending Reel',
    desc: 'Viral-format reel boosting reach organically.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'reel-005',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DZXrbjuKJQq/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781173035/Image-108_swiu5c.jpg',
    title: 'Trending Reel',
    desc: 'Viral-format reel boosting reach organically.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'reel-006',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DY4eKqeKfKb/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781173188/Image-802_icfcot.jpg',
    title: 'Trending Reel',
    desc: 'Viral-format reel boosting reach organically.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'post-001',
    cat: 'Content Creation',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/p/APNA_POST_ID/',
    thumb: '',
    title: 'Brand Post Design',
    desc: 'Eye-catching carousel for brand awareness.',
    year: '2024',
    aspect: 'square',
  },
  {
    id: 'video-001',
    cat: 'Video Production',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DXjoW3XiDpC/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781172069/Image-363_echnip.jpg',
    title: 'Corporate Brand Film',
    desc: 'Full corporate ad — concept to final edit.',
    year: '2024',
    aspect: 'landscape',
  },
  {
    id: 'meta-001',
    cat: 'Meta Ads',
    platform: 'facebook',
    postUrl: 'https://www.facebook.com/APNA_POST_LINK',
    thumb: '',
    title: 'Meta Lead Gen Campaign',
    desc: 'Audience-targeted campaign with 3x ROAS.',
    year: '2024',
    aspect: 'landscape',
  },
  {
    id: 'meta-002',
    cat: 'Meta Ads',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/p/APNA_POST_ID/',
    thumb: '',
    title: 'Instagram Ad Creative',
    desc: 'Story + feed ad set driving qualified leads.',
    year: '2024',
    aspect: 'square',
  },
  {
    id: 'reel-004',
    cat: 'Reels',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DEkdYrQS_CM/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781164176/Image-172_ppnfom.jpg',
    title: 'Festival Reel',
    desc: 'Festive season reel for brand engagement.',
    year: '2024',
    aspect: 'portrait',
  },
  {
    id: 'google-001',
    cat: 'Google Ads',
    platform: 'youtube',
    postUrl: 'https://www.youtube.com/watch?v=APNA_VIDEO_ID',
    thumb: '',
    title: 'Google Ads Video',
    desc: 'Search & display campaign with optimised CTR.',
    year: '2024',
    aspect: 'landscape',
  },
  {
    id: 'brand-001',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: '/image-001.png',
    thumb: '/image-001.png',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-002',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: '/image-002.png',
    thumb: '/image-002.png',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-003',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: '/image-003.png',
    thumb: '/image-003.png',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-004',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQ1o-LJCMHz/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781165075/Image-580_zfx3rk.jpg',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-005',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DOd3UNsDEzl/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781165982/Image-509_fhvbnh.jpg',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-006',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQosqYKiFyd/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781166502/Image-537_fqa5j6.jpg',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-007',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQ1RHdGjF4c/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781170385/Image-946_egkrdg.jpg',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-008',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQopY99Emy0/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781170797/Image-725_oboktm.jpg',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'brand-009',
    cat: 'Brand Identity',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/reel/DQ69OrPiJox/?utm_source=ig_web_button_share_sheet',
    thumb: 'https://res.cloudinary.com/dppcmxdhi/image/upload/v1781170964/Image-894_yfrssf.jpg',
    title: 'Brand Visual Identity',
    desc: 'Logo, color palette, typography and templates.',
    year: '2023',
    aspect: 'square',
  },
  {
    id: 'content-001',
    cat: 'Content Creation',
    platform: 'instagram',
    postUrl: 'https://www.instagram.com/p/APNA_POST_ID/',
    thumb: '',
    title: 'Social Content Strategy',
    desc: 'Monthly content boosting engagement by 200%.',
    year: '2024',
    aspect: 'square',
  },
  {
    id: 'film-001',
    cat: 'Film Direction',
    platform: 'youtube',
    postUrl: 'https://www.youtube.com/watch?v=APNA_VIDEO_ID',
    thumb: '',
    title: 'Corporate Ad Direction',
    desc: 'On-location corporate ad directed end-to-end.',
    year: '2023',
    aspect: 'landscape',
  },
]

export const CATS = [
  'All',
  'Reels',
  'Video Production',
  'Meta Ads',
  'Google Ads',
  'Brand Identity',
  'Content Creation',
  'Film Direction',
]
